# Generated by Django 5.2.3 on 2026-04-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal_uploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField()),
                ('journal_description', models.TextField()),
                ('journal_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='journal_videos/')),
                ('journal_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journal_uploaded')),
            ],
        ),
    ]
