# Generated by Django 5.2.3 on 2026-04-05 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_uploaded',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal_uploaded',
            name='journal_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='journal_uploaded',
            constraint=models.UniqueConstraint(fields=('owner', 'journal_title'), name='unique_journal_title_per_user'),
        ),
    ]
