# Generated by Django 5.2.3 on 2026-04-07 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_uploaded_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_uploaded',
            name='journal_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
